DATA:
  NUM_FRAMES: 16                      
  SAMPLING_RATE: 2
  INPUT_CHANNEL_NUM: [3]

MODEL:
  ARCH: i3d
  MODEL_NAME: I3D
  NUM_CLASSES: 7
  DROPOUT_RATE: 0.5

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200

RESNET:
  DEPTH: 50
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  ZERO_INIT_FINAL_BN: True
  STRIDE_1X1: False
  TRANS_FUNC: bottleneck_transform
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]

TRAIN:
  ENABLE: True
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  CHECKPOINT_PATH: checkpoints/

SOLVER:
  BASE_LR: 0.0001
  MAX_EPOCH: 30
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: adam

OUTPUT: output.json
TENSORBOARD: False