DATA:
  NUM_FRAMES: 16                      
  SAMPLING_RATE: 2
  INPUT_CHANNEL_NUM: [3]
  TRAIN_CROP_SIZE: 256
  MEAN: [0.395, 0.396, 0.397]
  STD: [0.250, 0.240, 0.200]

MODEL:
  PRETRAIN: False
  PRETRAIN_FILE: pretrain/R2PLUS1D_16x4_R50.pyth
  ARCH: r2plus1d
  MODEL_NAME: R2plus1D
  NUM_CLASSES: 7
  DROPOUT_RATE: 0.3

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200

RESNET:
  DEPTH: 50
  WIDTH_PER_GROUP: 64
  ZERO_INIT_FINAL_BN: True

TRAIN:
  ENABLE: True
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  CHECKPOINT_PATH: checkpoints/r2plus1d/

SOLVER:
  BASE_LR: 0.0005
  WARMUP: False
  WARMUP_EPOCHS: 10
  EPOCHS: 30
  SCHEDULE: none # cosine or multistep
  SCHEDULE_STEPS: [13, 16, 19]
  SCHEDULE_GAMMA: 0.1
  WEIGHT_DECAY: 1e-4  # 好
  OPTIMIZING_METHOD: adam

FEATURES:
  CHECKPOINT: checkpoints/r2plus1d/save_5.pth
  EXTRACT: False
  FRAMES_PATH: data/xxxxx/frames/
  STRIDE: 1
  
OUTPUT: output.json
TENSORBOARD: False