DATA:
  NUM_FRAMES: 16                      
  SAMPLING_RATE: 2
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.395, 0.396, 0.397]
  STD: [0.250, 0.240, 0.200]

MODEL:
  PRETRAIN: False
  PRETRAIN_FILE: pretrain/SLOWFAST.pyth
  ARCH: slowfast
  MODEL_NAME: SlowFast
  NUM_CLASSES: 7
  DROPOUT_RATE: 0.5

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

TRAIN:
  ENABLE: True
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  CHECKPOINT_PATH: checkpoints/slowfast/

SOLVER:
  BASE_LR: 0.01
  WARMUP: False
  WARMUP_EPOCHS: 10
  EPOCHS: 30
  SCHEDULE: cosine  # or multistep
  SCHEDULE_STEPS: [10, 20, 30]
  SCHEDULE_GAMMA: 0.1
  WEIGHT_DECAY: 1e-3
  OPTIMIZING_METHOD: adam

FEATURES:
  CHECKPOINT: checkpoints/slowfast/save_5.pth
  EXTRACT: False
  FRAMES_PATH: data/xxxxx/frames/
  STRIDE: 1

OUTPUT: output.json
TENSORBOARD: False