DATA:
  NUM_FRAMES: 16                      
  SAMPLING_RATE: 2
  INPUT_CHANNEL_NUM: [3]

MODEL:
  ARCH: x3d
  MODEL_NAME: X3D
  NUM_CLASSES: 7
  DROPOUT_RATE: 0.5

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
  
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

TRAIN:
  ENABLE: True
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  CHECKPOINT_PATH: checkpoints/x3d/

SOLVER:
  BASE_LR: 0.0001
  MAX_EPOCH: 30
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: adam

OUTPUT: output.json
TENSORBOARD: False