DATA:
  NUM_FRAMES: 16                      
  SAMPLING_RATE: 2
  INPUT_CHANNEL_NUM: [3]
  TRAIN_CROP_SIZE: 256
  MEAN: [0.395, 0.396, 0.397]
  STD: [0.250, 0.240, 0.200]

MODEL:
  PRETRAIN: True
  PRETRAIN_FILE: pretrain/X3D_M.pyth
  ARCH: x3d
  MODEL_NAME: X3D
  NUM_CLASSES: 7
  DROPOUT_RATE: 0.3  # 好

BN:
  USE_PRECISE_STATS: True  # True更好
  NUM_BATCHES_PRECISE: 200

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
  
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

TRAIN:
  ENABLE: True
  BATCH_SIZE: 32
  NUM_WORKERS: 8
  CHECKPOINT_PATH: checkpoints/x3d_m/

SOLVER:
  BASE_LR: 0.0005
  WARMUP: False
  WARMUP_EPOCHS: 10
  EPOCHS: 30
  SCHEDULE: none # cosine or multistep
  SCHEDULE_STEPS: [13, 16, 19]
  SCHEDULE_GAMMA: 0.1
  WEIGHT_DECAY: 1e-4  # 好
  OPTIMIZING_METHOD: adam

FEATURES:
  CHECKPOINT: checkpoints/x3d_m/save_5.pth
  EXTRACT: False
  FRAMES_PATH: data/xxxxx/frames/
  STRIDE: 1

OUTPUT: output.json
TENSORBOARD: False